name: finance_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_credit_card: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
          # style: italic
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Black.ttf
        - asset: assets/fonts/SourceSansPro-Light.ttf
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
        - asset: assets/fonts/SourceSansPro-BlackItalic.ttf
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf


    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
